#this file must be named gitstuarepoinit.yml and must be located in a repository 
# named .github in a folder named .github
# example file path: https://github.com/DadsTaxi/.github/tree/main/.github

# This can be expanded later however the only values which are set on a new repository or an existing repository on which the GitHub App is installed is:
# - required_approving_review_count
#

branches:
  - name: null
    protection:
      enforce_admins: null
      required_pull_request_reviews:
        required_approving_review_count: 2
      
